module Rubot
  module ApplicationCommand
    def add_application_command: (command: Hash[Symbol, String], subcommand: Hash[Symbol, String] | nil, group: String | nil) -> void
    def launch_application_commands: -> []
  end
end
