module Rubot
  class Command
    attr_reader props: Hash[Symbol, String]
    attr_reader execute: Proc

    def initialize: (Proc, name: String) -> void
    def []: (String) -> String
    def []=: (String, String) -> String
  end
end