module Rubot
  class Manager
    attr_accessor application_commands_path: String
    attr_accessor commands_path: String?
    attr_accessor events_path: String?

    def initialize: (application_commands_path: String, commands_path: String?, events_path: String?) -> void
    def files: (String) -> Array[String]
    def load_commands: (Array[String]) -> void
    def commands_files: -> Array[String]?
    def events_files: -> Array[String]?
    def application_commands_files: -> Array[String]
    def load: -> bool
  end
end
